src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use DateTimeInterface;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?DateTimeInterface $start = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?DateTimeInterface $end = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?DateTimeInterface $updated_at = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Announce $announce = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(nullable: true)]
    private ?float $diff_price = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStart(): ?DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getAnnounce(): ?Announce
    {
        return $this->announce;
    }

    public function setAnnounce(?Announce $announce): self
    {
        $this->announce = $announce;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDiffPrice(): ?float
    {
        return $this->diff_price;
    }

    public function setDiffPrice(?float $diff_price): self
    {
        $this->diff_price = $diff_price;

        return $this;
    }
}

src/Controller/Front/AnnounceController.php
<?php

namespace App\Controller\Front;

use App\Entity\Announce;
use App\Entity\Hotel;
use App\Entity\Reservation;
use App\Form\AnnounceType;
use App\Form\ReservationType;
use App\Repository\AnnounceRepository;
use App\Repository\ReservationRepository;
use App\Repository\UserRepository;
use DateTimeImmutable;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;

#[Route('/announce')]
class AnnounceController extends AbstractController
{
    #[Route('/', name: 'app_announce_index', options: ['sitemap' => true], methods: ['GET'])]
    public function index(
        Request $request,
        AnnounceRepository $announceRepository,
        PaginatorInterface $paginator
    ): Response
    {
        $paginatedAnnounce = $paginator->paginate(
            $announceRepository->findAll(),
            $request->query->getInt('page', 1),
            10
        );

        return $this->render('front/announce/index.html.twig', [
            'announces' => $paginatedAnnounce,
        ]);
    }

    #[Route('/search', name: 'default_announce_search', options: ['sitemap' => false], methods: ['POST'])]
    public function propertiesSearch(AnnounceRepository $announceRepository, Request $request): JsonResponse
    {
        $searchValue = $request->request->get('search');
        $searchResults = $announceRepository->search($searchValue);
        $searchResultsArray = [];

        foreach ($searchResults as $announce) {
            $searchResultsArray[] = [
                'getId' => $announce->getId(),
                'image' => $announce->getHotel()->getImage(),
                'name' => $announce->getTitle(),
                'price' => $announce->getPrice(),
                'nbBeds' => $announce->getNumberOfBeds()
            ];
        }

        return new JsonResponse($searchResultsArray);
    }

    #[Route('/{id}', name: 'app_announce_show', methods: ['GET', 'POST'])]
    public function show(Announce $announce, Request $request, ReservationRepository $reservationRepository, UserRepository $userRepository): Response
    {
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);
        }
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $user = $userRepository->findOneBy([
                'email' => $this->getUser()->getEmail(),
            ]);
            $reservation->setAnnounce($announce);
            $start = $reservation->getStart();
            $end = $reservation->getEnd();
            $verif = $reservationRepository->findBy(['announce' => $reservation->getAnnounce()]);
            $i = 0;
            if ($start > $end) {
                $i = 2;
            }
            foreach ($verif as $verification) {
                $debut = $verification->getStart();
                $fin = $verification->getEnd();
                if (($start < $debut && $end < $debut) || ($start > $fin && $end > $fin)) {
                } else {
                    $i = 1;
                }
            }
            if ($i == 0) {
                $reservation->setUser($user);
                $reservation->setCreatedAt(new DateTimeImmutable('now'));
                $number_days = date_diff($start, $end)->format('%a');
                $price = ($announce->getPrice()) * $number_days;
                $reservation->setPrice($price);
                $reservationRepository->save($reservation, true);
                return $this->redirectToRoute('front_app_payment', ['id' => $reservation->getId()], Response::HTTP_SEE_OTHER);
            } elseif ($i == 2) {
                $this->addFlash("error", "Please choose the correct start date");
            } else {
                $this->addFlash("error", "Please choose other dates");
            }

        }

        return $this->render('front/announce/show.html.twig', [
            'announce' => $announce,
            'hotel' => $announce->getHotel(),
            'form' => $form,
            'reservation' => $reservation,
        ]);
    }
}

src/Controller/Front/CommentController.php
<?php

namespace App\Controller\Front;

use App\Entity\Comment;
use App\Entity\User;
use App\Form\CommentType;
use App\Repository\CommentRepository;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/comment')]
class CommentController extends AbstractController
{
    #[Route('/', name: 'app_comment_index', methods: ['GET'])]
    public function index(CommentRepository $commentRepository): Response
    {
        return $this->render('front/comment/index.html.twig', [
            'comment' => $commentRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_comment_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CommentRepository $commentRepository): Response
    {
        if(!$this->getUser()){
            return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);
        }
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->get('user')->setData($this->getUser('id'));
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setCreatedAt(new DateTime());
            $commentRepository->save($comment, true);
            return $this->redirectToRoute('front_app_comment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('front/comment/new.html.twig', [
            'comment' => $comment,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_comment_show', methods: ['GET'])]
    public function show(Comment $comment): Response
    {
        return $this->render('front/comment/show.html.twig', [
            'comment' => $comment,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_comment_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Comment $comment, CommentRepository $commentRepository): Response
    {
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $commentRepository->save($comment, true);

            return $this->redirectToRoute('front_app_comment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('front/comment/edit.html.twig', [
            'comment' => $comment,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_comment_delete', methods: ['POST'])]
    public function delete(Request $request, Comment $comment, CommentRepository $commentRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$comment->getId(), $request->request->get('_token'))) {
            $commentRepository->remove($comment, true);
        }

        return $this->redirectToRoute('front_app_comment_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Front/DefaultController.php
<?php

namespace App\Controller\Front;

use App\Repository\CommentRepository;
use App\Repository\HotelRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
     #[Route('/', name: 'default_index', options: ['sitemap' => true])]
    public function index(HotelRepository $hotelRepository, CommentRepository $commentRepository): Response
    {
        $hotels = $hotelRepository->sortByRating();
        $hotelsNote = [];
        foreach ($hotels as $hotel){
            $hotelsNote[] = $commentRepository->getNbNote($hotel->getId());
        }
        return $this->render('front/default/index.html.twig', [
            'hotels' => $hotels,
            'nbNotes' => $hotelsNote
        ]);
    }

    #[Route('/about-us', name: 'default_about-us', options: ['sitemap' => true])]
    public function contact(): Response
    {
        return $this->render('front/default/about.html.twig');
    }

    #[Route('/privacy', name: 'default_privacy', options: ['sitemap' => true])]
    public function privacy(): Response
    {
        return $this->render('front/default/privacy.html.twig');
    }
}

src/Controller/Front/HotelController.php
<?php

namespace App\Controller\Front;

use App\Entity\Announce;
use App\Entity\Comment;
use App\Entity\Hotel;
use App\Form\CommentType;
use App\Repository\AnnounceRepository;
use App\Repository\CommentRepository;
use App\Repository\HotelRepository;
use App\Repository\ReservationRepository;
use App\Repository\UserRepository;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;

#[Route('/hotel')]
class HotelController extends AbstractController
{
    #[Route('/', name: 'app_hotel_index', options: ['sitemap' => true], methods: ['GET'])]
    public function index(
        Request            $request,
        HotelRepository    $hotelRepository,
        PaginatorInterface $paginator
    ): Response
    {
        $paginatedHotel = $paginator->paginate(
            $hotelRepository->findBy(["isValidated" => true]),
            $request->query->getInt('page', 1),
            10
        );

        return $this->render('front/hotel/index.html.twig', [
            'hotels' => $paginatedHotel,
        ]);
    }

    #[Route('/search', name: 'default_hotel_search', options: ['sitemap' => false], methods: ['POST'])]
    public function propertiesSearch(HotelRepository $hotelRepository, Request $request): JsonResponse
    {
        $searchValue = $request->request->get('search');
        $searchResults = $hotelRepository->search($searchValue);
        $searchResultsArray = [];

        foreach ($searchResults as $hotel) {
            $searchResultsArray[] = [
                'getId' => $hotel->getId(),
                'name' => $hotel->getName(),
                'city' => $hotel->getVille(),
                'note' => $hotel->getNote(),
                'country' => $hotel->getCountry(),
                'image' => $hotel->getImage(),
            ];
        }

        return new JsonResponse($searchResultsArray);
    }

    #[Route('/{id}', name: 'app_hotel_show', methods: ['GET', 'POST'])]
    public function show(Hotel $hotel, HotelRepository $hotelRepository, ReservationRepository $reservationRepository, CommentRepository $avisRepository, Request $request, UserRepository $userRepository): Response
    {
        $total_note = $hotel->getNote();
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        $exists = false;
        if ($this->getUser()){
            $reservations = $reservationRepository->findBy(['user' => $this->getUser()->getId()]);
            foreach ($reservations as $reservation) {
                if ($reservation->getAnnounce()->getHotel()->getId() === $hotel->getId()) {
                    $exists = true;
                }
            }
        }

        if ($form->isSubmitted() && $form->isValid()) {
            if (!$this->getUser()) {
                return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);
            }
            $user = $userRepository->findOneBy([
                'email' => $this->getUser()->getEmail(),
            ]);
            $comment->setUser($user);
            $comment->setHotel($hotel);
            $comment->setCreatedAt(new DateTime());
            $new_note = $comment->getNote();
            $nb_note = $avisRepository->getNbNote($hotel->getId());
            $total_old_note = $avisRepository->getTotalNote($hotel->getId());
            $total_note = ($new_note + $total_old_note) / ($nb_note + 1);
            $hotel->setNote($total_note);
            $avisRepository->save($comment, true);
            $hotelRepository->save($hotel, true);
            $this->addFlash('success', 'Votre commentaire a bien été ajouté');
            return $this->redirectToRoute('front_app_hotel_show', ['id' => $hotel->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->render('front/hotel/show.html.twig', [
            'comment' => $comment,
            'form' => $form,
            'hotel' => $hotel,
            'comments' => $avisRepository->findBy(array('hotel' => $hotel->getId())),
            'announces' => $hotel->getAnnounces(),
            'total_note' => $total_note,
            'exists'=>$exists
        ]);
    }
}

templates/front/reservation/_delete_form.html.twig
<form method="post" action="{{ path('front_app_reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this reservation ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn-danger" style="margin-top: 30px">Cancel Recervation</button>
</form>

templates/front/reservation/_form.html.twig
{{ form_start(form, {'attr': {'method': 'POST', 'enctype' : 'multipart/form-data'}})}}
    <div class="flex flex-col gap-3">
        {{ form_row(form.start, {'label_attr': {'class': 'mr-3 text-lg font-bold'}}) }}
        {{ form_row(form.end, { 'label_attr': {'class': 'mr-[1.35rem] text-lg font-bold'}}) }}
        {{ form_row(form.name, { 'label_attr': {'class': 'mr-4 text-lg font-bold'}})}}
    </div>
    <button class="btn-primary">{{ button_label|default('RESERVER') }}</button>
{{ form_end(form) }}

templates/front/reservation/edit.html.twig
{% extends 'base_front.html.twig' %}
{% block title %}Edit Reservation{% endblock %}

{% block main %}

    {{ include('front/reservation/_form.html.twig', {'button_label': 'Update'}) }}
    <br><br>
    <a class="btn-primary" href="{{ path('front_app_reservation_index') }}">My Reservations</a>
    {{ include('front/reservation/_delete_form.html.twig') }}
{% endblock %}

templates/front/reservation/index.html.twig
{% extends 'base_front.html.twig' %}
{% block title %}{{ app_name }} - Mes Réservations{% endblock %}
{% block main %}
    <div class="py-10 bg-gray-150">
        <div id="hotelContainer" class="mx-auto grid max-w-6xl  grid-cols-1 gap-6 p-6 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-2">
            {% for reservation in reservations %}
                <article class="flex justify-between rounded-xl bg-white p-3 shadow-lg hover:shadow-xl hover:transform  duration-300 ">
                    <div>
                        <h2 class="font-bold text-xl p-2">Booking name : {{ reservation.name }}</h2>
                        <div class="mt-1 p-2">
                            <h3 class="text-slate-700"><strong>Booking date : {{ reservation.createdAt ? reservation.createdAt|date('Y-m-d H:i:s') : '' }}</strong></h3>
                            <h3 class="text-slate-700"><strong>Price : {{ reservation.price }}€</strong></h3>
                            <h3 class="text-slate-700"><strong>{{ reservation.start ? reservation.start|date('Y-m-d') : '' }} TO {{ reservation.end ? reservation.end|date('Y-m-d') : '' }}</strong></h3>
                        </div>
                        <br>
                        <br>
                        <div>
                            <a class="btn-secondary" href="{{ path('front_app_reservation_show', {'id': reservation.id}) }}">Voir</a>
                            <a class="btn-primary" href="{{ path('front_reservation.pdf', {'id': reservation.id}) }}">PDF</a>
                        </div>
                    </div>
                    <div>
                        <img class="max-h-[150px] rounded-xl" src="{{ reservation.announce.hotel.image}}" alt="{{ reservation.announce.hotel.name}}">
                    </div>
                    
                </article>
            {% else %}
               <span>No reservation found</span>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/front/reservation/new.html.twig
{% extends 'base_front.html.twig' %}
{% block title %}{{ app_name }} - Reservation{% endblock %}

{% block main %}
    <table class="table mb-5">
        <thead class="border-b">
        <tr>
            <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Hotel</th>
            <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Prix</th>
            <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Title</th>
            <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Description</th>
            <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Bed</th>
            <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Options</th>
        </tr>
        </thead>
        <tbody>
            <tr class="border-b">
                <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">{{ announce.hotel }}</td>
                <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">{{ announce.price }} / Day</td>
                <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">{{ announce.title }}</td>
                <td class="text-sm text-gray-900 font-light px-6 py-4">{{ announce.description }}</td>
                <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">{{ announce.numberOfBeds }}</td>
                <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">{{ announce.options }}</td>
            </tr>
        </tbody>
    </table>
    {{ include('front/reservation/_form.html.twig') }}
    <br><br>
    <a class="btn-primary" href="{{ path('front_app_reservation_index') }}">My Reservations</a>
{% endblock %}

templates/front/reservation/pdf.html.twig
<!DOCTYPE html>
<html lang="" dir="ltr">
<head>
    <title>{% block title %}My Reservations{% endblock %}</title>
    {% include 'partials/_head.html.twig' %}
</head>
{% block body %}
    {% block header %}
        <nav>
            <div>
                <select></select>
            </div>
        </nav>
    {% endblock %}
    {% block main %}
        <div style="text-align: center">
            <h1 >Reservation</h1>
            <h3>Hello, We are pleased to confirm your reservation with HOTELIA</h3>
        </div>
        <div style="text-align: center">
            <table class="table mb-5" >
                <thead class="border-b" style="text-align: center">
                <tr>
                    <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Start Day</th>
                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">{{ reservation.start ? reservation.start|date('Y-m-d') : '' }}</td>
                </tr>
                <tr>
                    <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">End date</th>
                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">{{ reservation.end ? reservation.end|date('Y-m-d') : '' }}</td>
                </tr><
                <tr>
                    <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Booking date</th>
                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">{{ reservation.createdAt ? reservation.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                </tr>
                <tr>
                    <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Booking Price</th>
                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">{{ reservation.price }} €</td>
                </tr>
                <tr>
                    <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Booking Name</th>
                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">{{ reservation.name }}</td>
                </tr>
            </table>
        </div>
        <div style="text-align: center">
            <h4>If you have any questions or special requests regarding your stay, please do not hesitate to contact us.</h4>
        </div>
    {% endblock %}
    {% block footer %}{% endblock %}
{% endblock %}
</html>

templates/front/reservation/show.html.twig
{% extends 'base_front.html.twig' %}
{% block title %}My Reservations{% endblock %}

{% block main %}
<div class="py-10 bg-gray-150">
    <div id="hotelContainer" class="mx-auto grid max-w-6xl  grid-cols-1 gap-6 p-6 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-2">
        <article class="flex justify-between rounded-xl bg-white p-3 shadow-lg hover:shadow-xl hover:transform  duration-300 ">
            <div>
                <h3 class="font-bold text-2xl"><i class="fa fa-home"></i> {{ announce }}</h3><br>
                <div class="mt-1 p-2">
                    <h2 class="text-slate-700"><strong>{{ reservation.name }}</strong></h2>
                    <h2 class="text-slate-700"><strong>Price : {{ reservation.price }}€</strong></h2>
                    <h2 class="text-slate-700"><strong>{{ reservation.start ? reservation.start|date('Y-m-d') : '' }} TO {{ reservation.end ? reservation.end|date('Y-m-d') : '' }}</strong></h2>
                </div>
                <h3 class="font-bold text-xl">Booking date : {{ reservation.createdAt ? reservation.createdAt|date('Y-m-d H:i:s') : '' }}</h3>
                <br><br>
                <div>
                    <a class="btn-danger" href="{{ path('front_app_reservation_edit', {'id': reservation.id}) }}">Modifier</a>
                    <a class="btn-primary" href="{{ path('front_reservation.pdf', {'id': reservation.id}) }}">PDF</a>
                    <a class="btn-primary" href="{{ path('front_app_reservation_index') }}">Mes reservations</a>
                </div>
            </div>
            <div>
                <img class="max-h-[150px] rounded-xl" src="{{ reservation.announce.hotel.image}}" alt="{{ reservation.announce.hotel.name}}">
            </div>
        </article>
    </div>
</div>





{% endblock %}