src/Entity/Hotel.php
<?php

namespace App\Entity;

use App\Repository\HotelRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HotelRepository::class)]
class Hotel
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255)]
    private ?string $ville = null;

    #[ORM\Column]
    private ?int $code_postal = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $telephone = null;

    #[ORM\Column(nullable: true)]
    private ?int $note = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    public function __toString()
    {
        return $this->name;
    }

    #[ORM\OneToMany(mappedBy: 'hotel', targetEntity: Announce::class)]
    private Collection $announces;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?DateTimeInterface $createdAt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?DateTimeInterface $updatedAt = null;

    #[ORM\Column]
    private ?bool $isValidated = false;

    #[ORM\Column(length: 255)]
    private ?string $iban = null;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'hotels')]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'hotel', targetEntity: Comment::class)]
    private Collection $comments;

    #[ORM\Column(length: 255)]
    private ?string $country = null;

    public function __construct()
    {
        $this->announces = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(int $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(?int $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }


    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, Announce>
     */
    public function getAnnounces(): Collection
    {
        return $this->announces;
    }

    public function addAnnounce(Announce $announce): self
    {
        if (!$this->announces->contains($announce)) {
            $this->announces->add($announce);
            $announce->setHotel($this);
        }

        return $this;
    }

    public function removeAnnounce(Announce $announce): self
    {
        if ($this->announces->removeElement($announce)) {
            // set the owning side to null (unless already changed)
            if ($announce->getHotel() === $this) {
                $announce->setHotel(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function isIsValidated(): ?bool
    {
        return $this->isValidated;
    }

    public function setIsValidated(bool $isValidated): self
    {
        $this->isValidated = $isValidated;

        return $this;
    }

    public function getIban(): ?string
    {
        return $this->iban;
    }

    public function setIban(string $iban): self
    {
        $this->iban = $iban;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setHotel($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getHotel() === $this) {
                $comment->setHotel(null);
            }
        }

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

}

src/Controller/Back/HotelController.php
<?php

namespace App\Controller\Back;

use App\Entity\Hotel;
use App\Entity\Announce;
use App\Form\HotelType;
use App\Repository\CommentRepository;
use App\Repository\HotelRepository;
use App\Repository\AnnounceRepository;
use App\Repository\ReservationRepository;
use App\Repository\PaymentRepository;
use App\Repository\RequestCustomerRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Knp\Component\Pager\PaginatorInterface;

#[Route('/hotel')]
class HotelController extends AbstractController
{
    #[Route('/', name: 'app_hotel_index', methods: ['GET'])]
    public function index(
        Request $request,
        HotelRepository $hotelRepository,
        PaginatorInterface $paginator
    ): Response
    {
        $paginatedHotel = $paginator->paginate(
            $hotelRepository->findAll(),
            $request->query->getInt('page', 1),
            10
        );

        return $this->render('back/hotel/index.html.twig', [
            'hotels' => $paginatedHotel,
            'page' => 'hotel',
        ]);
    }

    #[Route('/{id}', name: 'app_hotel_show', methods: ['GET'])]
    public function show(Hotel $hotel): Response
    {
        return $this->render('back/hotel/show.html.twig', [
            'hotel' => $hotel,
            'page' => 'hotel',
        ]);
    }

    #[Route('/{id}/remove/{token}', name: 'app_hotel_delete', methods: ['GET'])]
    public function delete(
        Request $request,
        Hotel $hotel,
        HotelRepository $hotelRepository,
        AnnounceRepository $announceRepository,
        CommentRepository $commentRepository,
        ReservationRepository $reservationRepository,
        PaymentRepository $paymentRepository,
        RequestCustomerRepository $requestCustomerRepository,
        string $token
    ): Response
    {
        if (!$this->isCsrfTokenValid('delete' . $hotel->getId(), $token)) {
            throw $this->createAccessDeniedException();
        }

        $hotelRepository->remove($hotel, true);
        $this->addFlash("success","L'hôtel a bien été supprimé");

        return $this->redirectToRoute('admin_app_hotel_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Customer/HotelController.php
<?php

namespace App\Controller\Customer;

use App\Entity\Comment;
use App\Entity\Hotel;
use App\Form\CommentType;
use App\Form\HotelType;
use App\Repository\CommentRepository;
use App\Repository\AnnounceRepository;
use App\Repository\HotelRepository;
use App\Repository\RequestCustomerRepository;
use App\Repository\UserRepository;
use App\Security\Voter\HotelVoter;
use DateTime;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Bundle\SecurityBundle\Security as SecurityBundle;
use Knp\Component\Pager\PaginatorInterface;

#[Route('/hotel'), IsGranted('ROLE_CUSTOMER')]
class HotelController extends AbstractController
{
    #[Route('/', name: 'app_hotel_index', methods: ['GET'])]
    public function index(
        Request $request,
        HotelRepository $hotelRepository, 
        SecurityBundle $security,
        PaginatorInterface $paginator
    ): Response
    {
        $paginatedHotel = $paginator->paginate(
            $hotelRepository->findBy(['user' => $security->getUser(),'isValidated'=>1]),
            $request->query->getInt('page', 1),
            10
        );

        return $this->render('customer/hotel/index.html.twig', [
            'hotels' => $paginatedHotel,
            'page' => 'hotel',
        ]);
    }

    #[Route('/new', name: 'app_hotel_new', methods: ['GET', 'POST'])]
    public function new(Request $request, HotelRepository $hotelRepository, SluggerInterface $slugger): Response
    {

        $hotel = new Hotel();
        $form = $this->createForm(HotelType::class, $hotel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $hotel->setUser($this->getUser());
            $hotel->setCreatedAt(new DateTime());
            $hotel->setUpdatedAt(new DateTime());
            $hotel->setIsValidated(1);
            $image = $form->get('image')->getData();
            if ($image) {
                $originalFilename = pathinfo($image->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $image->guessExtension();
                $pathFile = '../../../uploads/image_hotel/' . $newFilename;

                try {
                    $image->move(
                        $this->getParameter('image_hotel'),
                        $newFilename
                    );
                } catch (FileException $e) {
                }
                $hotel->setImage($pathFile);
            }

            $hotelRepository->save($hotel, true);

            return $this->redirectToRoute('customer_app_hotel_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('customer/hotel/new.html.twig', [
            'hotel' => $hotel,
            'form' => $form,
            'page' => 'hotel',
        ]);
    }

    #[Route('/{id}', name: 'app_hotel_show', methods: ['GET', 'POST'])]
    #[IsGranted(HotelVoter::SHOW, 'hotel')]
    public function show(Hotel $hotel, HotelRepository $hotelRepository, CommentRepository $avisRepository, Request $request, UserRepository $userRepository): Response
    {
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);
        }
        $total_note = $hotel->getNote();
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $user = $userRepository->findOneBy([
                'email' => $this->getUser()->getEmail(),
            ]);
            $comment->setUser($user);
            $comment->setHotel($hotel);
            $new_note = $comment->getNote();
            $nb_note = $avisRepository->getNbNote();
            $total_old_note = $avisRepository->getTotalNote();
            $total_note = ($new_note + $total_old_note) / ($nb_note + 1);
            $hotel->setNote($total_note);
            $avisRepository->save($comment, true);
            $hotelRepository->save($hotel, true);
        }

        return $this->render('customer/hotel/show.html.twig', [
            'comment' => $comment,
            'form' => $form,
            'hotel' => $hotel,
            'comments' => $avisRepository->findBy(array('hotel' => $hotel->getId())),
            'total_note' => $total_note,
            'page' => 'hotel',
        ]);
    }

    #[Route('/{id}/edit', name: 'app_hotel_edit', methods: ['GET', 'POST'])]
    #[IsGranted(HotelVoter::EDIT, 'hotel')]
    public function edit(Request $request, Hotel $hotel, HotelRepository $hotelRepository, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(HotelType::class, $hotel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $image = $form->get('image')->getData();
            if ($image) {
                $originalFilename = pathinfo($image->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $image->guessExtension();
                $pathFile = '../../../uploads/image_hotel/' . $newFilename;
                try {
                    $image->move(
                        $this->getParameter('image_hotel'),
                        $newFilename
                    );
                } catch (FileException $e) {
                }
                $hotel->setImage($pathFile);
            }
            $hotelRepository->save($hotel, true);

            return $this->redirectToRoute('customer_app_hotel_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('customer/hotel/edit.html.twig', [
            'hotel' => $hotel,
            'form' => $form,
            'page' => 'hotel'
        ]);
    }

    #[Route('/{id}/remove/{token}', name: 'app_hotel_delete', methods: ['GET'])]
    #[IsGranted(HotelVoter::DELETE, 'hotel')]
    public function delete(
        Request $request,
        Hotel $hotel,
        HotelRepository $hotelRepository,
        AnnounceRepository $announceRepository,
        CommentRepository $commentRepository,
        RequestCustomerRepository $requestCustomerRepository,
        string $token
    ): Response
    {
        if (!$this->isCsrfTokenValid('delete' . $hotel->getId(), $token)) {
            throw $this->createAccessDeniedException();
        }

        $hotelRepository->remove($hotel, true);
        $this->addFlash("success","L'hôtel a bien été supprimé");

        return $this->redirectToRoute('customer_app_hotel_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Front/DefaultController.php
<?php

namespace App\Controller\Front;

use App\Repository\CommentRepository;
use App\Repository\HotelRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
     #[Route('/', name: 'default_index', options: ['sitemap' => true])]
    public function index(HotelRepository $hotelRepository, CommentRepository $commentRepository): Response
    {
        $hotels = $hotelRepository->sortByRating();
        $hotelsNote = [];
        foreach ($hotels as $hotel){
            $hotelsNote[] = $commentRepository->getNbNote($hotel->getId());
        }
        return $this->render('front/default/index.html.twig', [
            'hotels' => $hotels,
            'nbNotes' => $hotelsNote
        ]);
    }

    #[Route('/about-us', name: 'default_about-us', options: ['sitemap' => true])]
    public function contact(): Response
    {
        return $this->render('front/default/about.html.twig');
    }

    #[Route('/privacy', name: 'default_privacy', options: ['sitemap' => true])]
    public function privacy(): Response
    {
        return $this->render('front/default/privacy.html.twig');
    }
}

templates/front/hotel/index.html.twig
{% extends 'base_front.html.twig' %}

{% block title %}{{ app_name }} - Liste des Hotels{% endblock %}

{% block main %}
    <div class="mb-3">
        <form>
            <label for="default-search" class="mb-2 text-sm font-medium sr-only dark:text-white">Search</label>
            <div class="relative">
                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                    <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="none"
                         stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                    </svg>
                </div>
                <input type="search" id="propertiesSearch"
                       class="block w-full p-4 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 focus:outline-none shadow  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:border-blue-500"
                       placeholder="Rechercher un hotel, une ville, un pays..."
                       value="{{ app.request.request.get('q') }}" required>
                <button type="submit"
                        class="text-white absolute right-2.5 bottom-2.5 bg-indigo-600 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                    Search
                </button>
            </div>
        </form>
    </div>
    <div class="py-10 bg-gray-50">
        <div id="hotelContainer"
             class="mx-auto grid max-w-6xl  grid-cols-1 gap-6 p-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-3">
            {% if hotels | length > 0 %}
                {% for hotel in hotels %}
                    <article
                            class="rounded-xl bg-white p-3 shadow-lg hover:shadow-xl hover:transform hover:scale-105 duration-300 ">
                        <a href="{{ path('front_app_hotel_show', {'id': hotel.id}) }}">
                            <div class="relative flex items-end overflow-hidden rounded-xl h-[340px]">
                                <img src="{{ hotel.image }}" class="w-fit h-full" alt="Hotel Photo" loading="lazy"
                                     srcset="{{ hotel.image }}">
                            </div>
                            <div class="mt-1 p-2">
                                <h2 class="text-slate-700">{{ hotel.name }}</h2>
                                <p class="mt-1 text-sm text-slate-400">{{ hotel.ville }}, {{ hotel.country }}</p>

                                <div class="mt-3 flex items-end justify-between">
                                    <p class="text-lg font-bold text-blue-500">
                                        {% for i in 1..hotel.note %}
                                            <i style="color: gold;" class="fa fa-star gold"></i>
                                        {% endfor %}</p>
                                    <div class="flex items-center space-x-1.5 rounded-lg bg-blue-500 px-4 py-1.5 text-white duration-100 hover:bg-blue-600">
                                        <button class="text-sm"><a
                                                    href="{{ path('front_app_hotel_show', {'id': hotel.id}) }}">Voir</a>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </article>
                {% endfor %}
            {% else %}
                <article>
                    Aucun Hotel n'est present
                </article>
            {% endif %}
        </div>
    </div>
    <div class="text-center">
        {{ knp_pagination_render(hotels) }}
    </div>
{% endblock %}

templates/front/hotel/show.html.twig
{% extends 'base_front.html.twig' %}
{% block title %}{{ app_name }} - Hotel {{ hotel.name }}{% endblock %}
{% block main %}
    <div class="py-10 bg-gray-150">
        <div id="hotelContainer"
             class="mx-auto grid max-w-6xl  grid-cols-1 gap-6 p-6 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-2">
            <article
                    class="rounded-xl bg-white p-3 shadow-lg hover:shadow-xl hover:transform hover:scale-105 duration-300 ">

                <div class="relative flex items-end overflow-hidden rounded-xl">
                    <img src="{{ hotel.image }}" class="w-fit h-full" alt="Hotel Photo" loading="lazy">
                </div>
                <div class="mt-1 p-2">
                    <h2 class="text-slate-700"><strong>{{ hotel.name }}</strong></h2>
                    <p class="mt-1 text-sm text-slate-400">{{ hotel.ville }}, {{ hotel.country }}</p>

                    <div class="mt-3 flex items-end justify-between">
                        <p class="text-lg font-bold text-blue-500">
                            {% for i in 1..hotel.note %}
                                <i style="color: gold;" class="fa fa-star gold"></i>
                            {% endfor %}</p>
                    </div>
                </div>
            </article>
            <div>
                <article style="background-color: #DDECF5" class="rounded-xl bg-white p-3 shadow-lg hover:shadow-xl">
                    <label><strong>Adresse : </strong></label>{{ hotel.adresse }}, {{ hotel.ville }}
                    , {{ hotel.codePostal }}<br>
                    <label><strong>Téléphone : </strong></label>{{ hotel.telephone }}<br>
                    <label><strong>Description : </strong></label>{{ hotel.description }}<br>
                </article>
                <br>
                <article style="background-color: #DDECF5" class="rounded-xl bg-white p-3 shadow-lg hover:shadow-xl">
                    <h3 class="font-bold text-2xl">{{ hotel.name }} Announces</h3><br>
                    {% for announce in announces %}
                        <div class="flex justify-between mb-[10px] items-center">
                            <div>
                                {{ announce.title }}
                            </div>
                            <div class="flex flex-row items-center justify-between gap-3">
                                <span class="font-semibold">{{ announce.price }} € / Jour</span>
                                <button class="btn-primary">
                                    <a href="{{ path('front_app_announce_show', {'id': announce.id}) }}">Check</a>
                                </button>
                            </div>
                        </div>
                    {% else %}
                        Aucune Annonce
                    {% endfor %}
                </article>
            </div>
        </div>
        <div id="hotelContainer"
             class="mx-auto grid max-w-6xl  grid-cols-1 gap-6 p-6 sm:grid-cols-1 md:grid-cols-1 lg:grid-cols-1">
            {% if app.user and exists == true %}
                <article style="background-color: #DDECF5" class="p-3 shadow-lg hover:shadow-xl">
                    <div>
                        <h2><strong>Post Comment</strong></h2><br>
                        {{ include('front/comment/_form.html.twig') }}
                    </div>
                </article><br>
            {% endif %}
            <article style="background-color: #DDECF5" class=" bg-white p-3 shadow-lg hover:shadow-xl">
                <h2><strong>Commentaires</strong></h2><br>
                {% for comment in comments %}
                    <div style="display: flex;justify-content: space-between">
                        <div class="w-5/6">
                            {{ comment.message }}
                        </div>
                        <div class="w-1/6 text-left">
                            {% for i in 1..comment.note %}
                                <i style="color: gold;" class="fa fa-star gold"></i>
                            {% endfor %}
                        </div>
                    </div>
                    <hr><br>
                {% else %}
                    Aucun Avis
                {% endfor %}
                <hr>
            </article>
            <button class="btn-primary"><a href="{{ path('front_app_hotel_index') }}">Liste des Hotels</a></button>
        </div>
    </div>

{% endblock %}